<?php
/**
 * Created by PhpStorm.
 * User: sohel
 * Date: 9/8/15
 * Time: 2:44 PM
 */

namespace App\Helpers;


class DataUtils
{
    const COMMENT_ENABLE = false;
    const INITIAL_CROWD_COINS = 100000;
    const PAID_MEMBERSHIP_AMOUNT = 12;

    public static $items = array('main'=>'Main','city'=> 'City', 'category_1'=> 'Category 1', 'category_2'=> 'Category 2', 'interest'=> 'Interest','my_idea'=>'My Idea');

    public static $interests = array(
        '3D printing'=>'3D printing',
        'Accounting' => 'Accounting',
        'Affiliate Marketing' =>  'Affiliate Marketing',
        'Animals'=> 'Animals',
        'Animation design' => 'Animation design',
        'Anime'=> 'Anime',
        'Art'=>'Art',
        'Beauty'=>'Beauty',
        'Blogging'=>'Blogging',
        'Blogging Tips'=>'Blogging Tips',
        'Budgeting'=>'Budgeting',
        'Business'=>'Business',
        'Cars' => 'Cars',
        'Coding'=>'Coding',
        'Computer programming' => 'Computer programming',
        'Copywriting' => 'Copywriting',
        'Crafts' => 'Crafts',
        'Crystals and Gemstones' => 'Crystals and Gemstones',
        'Dancing' => 'Dancing',
        'Dating  Romance' => 'Dating  Romance',
        'debate'=> 'debate',
        'design'=>'design' ,
        'DIY'=> 'DIY',
        'DJ'=> 'DJ',
        'Education'=> 'Education',
        'engineering'=> 'engineering',
        'Entertainment'=> 'Entertainment',
        'environment'=> 'environment',
        'Family'=> 'Family',
        'fanfiction'=> 'fanfiction',
        'Fashion  Shopping'=> 'Fashion  Shopping',
        'finacial'=> 'finacial',
        'Finance  Law'=> 'Finance  Law',
        'extreme sports'=> 'extreme sports',
        'Food'=> 'Food',
        'gadgets and electronics'=> 'gadgets and electronics',
        'concertsevents'=> 'concertsevents',
        'Gaming'=> 'Gaming',
        'gardening'=> 'gardening',
        'genealogy'=> 'genealogy',
        'geocaching'=> 'geocaching',
        'ghost hunting'=> 'ghost hunting',
        'golfing'=> 'golfing',
        'graphic design'=> 'graphic design',
        'Green'=> 'Green',
        'Gun Collecting'=> 'Gun Collecting',
        'Gymnastics'=> 'Gymnastics',
        'Gyotaku'=> 'Gyotaku',
        'Handwriting Analysis'=> 'Handwriting Analysis',
        'Hang gliding'=>'Hang gliding' ,
        'health'=> 'health',
        'Home decor'=> 'Home decor',
        'Horse Riding'=> 'Horse Riding',
        'Impersonations'=>'Impersonations' ,
        'Infographics'=> 'Infographics',
        'Internet'=> 'Internet',
        'Inventing'=> 'Inventing',
        'investing'=> 'investing',
        'languages'=> 'languages',
        'law'=> 'law',
        'Lifestyle'=> 'Lifestyle',
        'magicillusion'=> 'magicillusion',
        'martial arts'=> 'martial arts',
        'medicine'=> 'medicine',
        'networking'=> 'networking',
        'Music'=> 'Music',
        'New Age'=> 'New Age',
        'Nonprofit'=> 'Nonprofit',
        'Offbeat'=> 'Offbeat',
        'outdoors and camping'=> 'outdoors and camping',
        'painting'=> 'painting',
        'Pets'=> 'Pets',
        'philosophy'=> 'philosophy',
        'Photography'=> 'Photography',
        'plants'=> 'plants',
        'podcasting'=> 'podcasting',
        'pyrotechnics'=> 'pyrotechnics',
        'reading and books'=> 'reading and books',
        'Real Estate'=> 'Real Estate',
        'recipes'=> 'recipes',
        'Religion'=> 'Religion',
        'robotics'=> 'robotics',
        'Self Improvement'=> 'Self Improvement',
        'shopping' => 'shopping',
         'social media'=> 'social media',
         'Society  Social Issues'=> 'Society  Social Issues',
         'Spirituality'=> 'Spirituality',
         'Sports  Fitness'=> 'Sports  Fitness',
         'supernaturaloccult'=> 'supernaturaloccult',
         'swimming'=> 'swimming',
         'Family'=> 'Family',
        'Technology' => 'Technology',
        'television' => 'television',
        'theatre' => 'theatre',
        'travel'=> 'travel',
        'video games'=> 'video games',
        'videography'=> 'videography',
        'volunteering'=> 'volunteering',
        'Web Design' => 'Web Design',
        'World News' => 'World News'

    );

    public static $cities = [
        'Abidjan Ivory Coast',
        'Addis Ababa Ethiopia',
        'Ahmadabad India',
        'Albuquerque New Mexico',
        'Alexandria Egypt',
        'Amman Jordan',
        'Anaheim California',
        'Anchorage municipality Alaska',
        'Ankara Turkey',
        'Arlington Texas',
        'Atlanta Georgia',
        'Auckland New Zealand',
        'Aurora Colorado',
        'Austin Texas',
        'Bakersfield California',
        'Baltimore Maryland',
        'Bandung Indonesia',
        'Bangalor India',
        'Bangkok Thailand',
        'Baoshan China',
        'Beijing China',
        'Beirut Lebanon',
        'Berlin Germany',
        'Bogota Colombia',
        'Boston Massachusetts',
        'Brussels Belgium',
        'Buenos Aires Argentina',
        'Buffalo New York',
        'Busan South Korea',
        'Cairo Egypt',
        'Calgary Alberta',
        'Cali Colombia',
        'Cape Town South Africa',
        'Caracua Venezuela',
        'Casablanca Morocco',
        'Changchun China',
        'Changsha China',
        'Charlotte North Carolina',
        'Chengdu China',
        'Chennai India',
        'Chicago Illinois',
        'Chittagong Bangledesh',
        'Chongqing China',
        'Chula Vista California',
        'Cincinnati Ohio',
        'Cleveland Ohio',
        'Colorado Springs Colorado',
        'Columbus Ohio',
        'Corpus Christi Texas',
        'Daegu South Korea',
        'Dallas Texas',
        'Dar Es Salaam Tanzania',
        'Delhi India',
        'Denver Colorado',
        'Detroit Michigan',
        'Dhaka Bangledesh',
        'Dongguan China',
        'Dubai UAE',
        'Durg India',
        'Edmonton Alberta',
        'El Paso Texas',
        'Faisalabad Pakistan',
        'Fort Wayne Indiana',
        'Fort Worth Texas',
        'Fortaleza Brazil',
        'Fresno California',
        'Greensboro North Carolina',
        'Guangzhou China',
        'Guiyang China',
        'Hamilton Ontario',
        'Hangzhou China',
        'Harbin China',
        'Helsinki',
        'Henderson Nevada',
        'Ho Chi Minh City Vietnam',
        'Hong Kong China',
        'Honolulu Hawaii',
        'Houston Texas',
        'Huludao China',
        'Hyderabad India',
        'Ibadan Nigeria',
        'Incheon South Korea',
        'Indianapolis Indiana',
        'Istanbul Turkey',
        'Jacksonville Florida',
        'Jakarta Indonesia',
        'Jeddah Saudi Arabia',
        'Jersey  New Jersey',
        'Johannesburg South Africa',
        'Kano Nigeria',
        'Kanpur China',
        'Kansas  Missouri',
        'Karachi Pakistan',
        'Keiv Ukraine',
        'Kinshasha Congo D.R.',
        'Kitchener Ontario',
        'Kolkata India',
        'Kumming China',
        'Lagos Nigeria',
        'Lahore Pakistan',
        'Las Vegas Nevada',
        'Lexington-Fayette Kentucky',
        'Lima Peru',
        'Lincoln Nebraska',
        'London UK',
        'Long Beach California',
        'Los Angeles California',
        'Louisville/Jefferson Kentucky',
        'Luanda Angola',
        'Madrid Spain',
        'Manila Phillipines',
        'Melbourne Australia',
        'Memphis Tennessee',
        'Mesa Arizona',
        'Mexico City Mexico',
        'Miami Florida',
        'Milwaukee Wisconsin',
        'Minneapolis Minnesota',
        'Montreal Quebec',
        'Moscow Russia',
        'Mumbai (Bombay) India',
        'Munich Germany',
        'Nairobi Kenya',
        'Nanjing China',
        'Nashville-Davidson Tennessee',
        'New Orleans Louisiana',
        'New York City New York',
        'Newark New Jersey',
        'Oakland California',
        'Oklahoma  Oklahoma',
        'Omaha Nebraska',
        'Orlando Florida',
        'Osaka Japan',
        'Ottawa Ontario',
        'Panama',
        'Paris France',
        'Perth Australia',
        'Philadelphia Pennsylvania',
        'Phoenix Arizona',
        'Pittsburgh Pennsylvania',
        'Plano Texas',
        'Port Harcourt Nigeria',
        'Portland Oregon',
        'Prague Czech Republic',
        'Pune India',
        'Qingdao China',
        'Quebec City Quebec',
        'Quezon City Philippines',
        'Raleigh North Carolina',
        'Rio de Janeiro  Brazil',
        'Riverside California',
        'Riyadh Saudi Arabia',
        'Rome Italy',
        'Sacramento California',
        'Salvador da Bahia Brazil',
        'San Antonio Texas',
        'San Diego California',
        'San Francisco California',
        'San Jose California',
        'Santa Ana California',
        'Santiago Chile',
        'Santo Domingo DR',
        'Sao Paulo Brazil',
        'Seattle Washington',
        'Seoul South Korea',
        'Shanghai China',
        'Shenyang China',
        'Shenzhen China',
        'Shreveport LA',
        'Siena Italy',
        'Singapore Singapore',
        'St. Louis Missouri',
        'St. Paul Minnesota',
        'St. Petersburg Russia',
        'Stockton California',
        'Surabaya Indonesia',
        'Surat India',
        'Sydney Australia',
        'Taipei Taiwan',
        'Taiyuan China',
        'Tampa Florida',
        'Tehran Iran',
        'Tel Aviv Israel',
        'Tianjin China',
        'Tokyo Japan',
        'Toledo Ohio',
        'Toronto Ontario',
        'Tucson Arizona',
        'Tulsa Oklahoma',
        'Vancouver British Columbia',
        'Vienna Austria',
        'Virginia Beach Virginia',
        'Washington DC',
        'Wichita Kansas',
        'Winnipeg Manitoba',
        'Wuhan China',
        'Xian China',
        'Yangon Myanmar (Burma)',
        'Yokohama Japan',
        'Zhengzhou China',
        'Zhongshan China',
        'Zibo China'
    ];

    public static $techCategories = [
        'Biotech',
        'Blogging',
        'Cleantech',
        'Crypto Currencies',
        'Education Tech',
        'Gamification',
        'Financial Tech',
        'Health Tech',
        'Location Tech',
        'Mobile Apps',
        'Online Tools',
        'Social Media'
    ];

    public static $manualUpgradeUserList = [
        'lastbabyboomer',
        'japanhealthtips',
        'sydesjokes',
        'exploretravel1',
        'gregweir',
        'The7PillarsBook',
        'crowdifytv',
        'momzilla254',
        'williampearl',
        'kirstenwrites',
        'vanwouw',
        'bluesbro',
        'techjewel',
        'randyhilarski',
        'dryorikotodd',
        'mqtodd',
        'crowdifytech',
        'crowdifygreen',
        'claytonjohnston',
        'anabellhilarski',
        'HIMGPanama',
        'momzilla254',
        'sohel_sohel_'
    ];
}